version: '3'
services:
  frontend:
    build:
      context: ./frontend
    dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}
