version: '3'
services:
  backend:
    build:
      context: ./backend
    dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trackmybus
    ports:
      - "5432:5432"
